package application;

public class ReportTitles {
	
	public static String reportTitle1 = "Customers who have spent more then a certain amount per month";
	
	public static String reportTitle2 = "Total revenue generated by each section";
	
	public static String reportTitle3 = "Revenue generated by each store at any time of year";
	
	public static String reportTitle4 = "Debit Cards mostly used";

	public static String reportTitle5 = "Products bought by people of certain age";
	
	public static String reportTitle6 = "Product with the highest sales in certain amount of time";
	
	public static String reportTitle7 = "Total sale of certain product at a certain store";
	
	public static String reportTitle8 = "Products not getting sold";
	
	public static String reportTitle9 = "Sales as per discounts for previous and current year";
	
	public static String reportTitle10 = "Suppliers giving the maximum revenue";
	
}
